version: '3.9'

services:
  dash:
    # This is for that asking the container to execute the main.py
    command: python3 main.py
    # The image I upload to my docker hub
    image: akraradets/ait-ml-dash:2023
    # For MAC M1 user
    platform: linux/x86_64
    # This will ask DASH to run on 0.0.0.0 and port 80
    environment:
      - HOST=0.0.0.0
      - PORT=80
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.<service_name>-<folder_name>.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is <service_name>-<folder_name>
      # If you which to change the subdomain name, you uncomment the below configuration
      # - traefik.http.routers.<service_name>-<folder_name>.rule=Host(`<subdomain>.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.<service_name>-<folder_name>.tls=true
      - traefik.http.routers.<service_name>-<folder_name>.tls.certresolver=production
      - traefik.http.routers.<service_name>-<folder_name>.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true